### ISSUE TITLE
Can you please get Lens available for International Archives of Medicine?

### ISSUE THREAD

**Issue by carvaper** [elifesciences/lens#107]
We are publishing International Archives of Medicine and we´d like to start using it.
We are publishing the journal using Open Journal Systems.

**Comment by michael** [comment]
While proper annotated XML files should work out of the box with Lens there's always some need for customization for individual journals. If there's interest in contracting developers from the Lens team to get up and running, please contact us via email.

Also, sorry for late reply on this.

**Comment by carvaper** [comment]
Dear Michael,
Thank you for your response. I´m not sure what your email is, so if this
email goes to someone different in eLifeSciences, please forward it to
Michael.
I´d like to get a quote on how much would cost to have Lens up and running
for our journals before I can confirm our request.
Thank you
Best,
Carlos



On 30 March 2015 at 20:08, Michael Aufreiter <notifications@github.com>
wrote:

> While proper annotated XML files should work out of the box with Lens
> there's always some need for customization for individual journals. If
> there's interest in contracting developers from the Lens team to get up and
> running, please contact us via email.
>
> Also, sorry for late reply on this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elifesciences/lens/issues/107#issuecomment-87776540>.
>



-- 

*Carlos Vázquez*
CEO iMedPub
iMed.pub

**Comment by michael** [comment]
You can find contact information here: http://substance.io/about

We've usually run through several stages when we deployed Lens for a new journal. 

1) A demo with a limited set of test articles (3-4 weeks dev)
2) A pilot that can be launched  (1-3 months dev)
3) Polish iterations (based on feature requests)
4) Official launch as soon as display quality meets the requirements

We charge on an hourly basis, and can provide estimates for individual work packages. How much budget is needed depends on how good the quality of the source XML files is and how many customisations are requested.

-- Michael

**Comment by carvaper** [comment]
Dear Michael,
Thank you for your reply.
Just out of curiosity, would it be possible to create a new publishing
platform as elifesciences.org? I mean a completely new one, not linked to
our previous publications. How much would it be?
Then we´ll be able to decide if we prefer to make Lens available for our
publications or creating a new label/publisher.
Thanks


On 1 April 2015 at 09:45, Michael Aufreiter <notifications@github.com>
wrote:

> You can find contact information here: http://substance.io/about
>
> We've usually run through several stages when we deployed Lens for a new
> journal.
>
> 1) A demo with a limited set of test articles (3-4 weeks dev)
> 2) A pilot that can be launched (1-3 months dev)
> 3) Polish iterations (based on feature requests)
> 4) Official launch as soon as display quality meets the requirements
>
> We charge on an hourly basis, and can provide estimates for individual
> work packages. How much budget is needed depends on how good the quality of
> the source XML files is and how many customisations are requested.
>
> -- Michael
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elifesciences/lens/issues/107#issuecomment-88382641>.
>



-- 

*Carlos Vázquez*
CEO iMedPub
iMed.pub

**Comment by ivangrub** [comment]
As an FYI, linking to previous CC-BY publications can be done on oa-sandbox.org too. An example article from your corpus: http://oa-sandbox.org/lens/?pmc=PMC4221686. We are simply pulling the XML files from PMC and rendering what we get back in Lens.

**Comment by carvaper** [comment]
Thanks Ivan, that's great! Can something similar be done with Google
Scholar instead of PMC?
Also how costly would be to clone the full elifesciences.org structure?

On 1 April 2015 at 14:54, Ivan Grubisic <notifications@github.com> wrote:

> As an FYI, linking to previous CC-BY publications can be done on
> oa-sandbox.org too. An example article from your corpus:
> http://oa-sandbox.org/lens/?pmc=PMC4221686. We are simply pulling the XML
> files from PMC and rendering what we get back in Lens.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elifesciences/lens/issues/107#issuecomment-88467981>.
>



-- 

*Carlos Vázquez*
CEO iMedPub
iMed.pub

**Comment by ivangrub** [comment]
Google Scholar only provides links to other resources where the article can be found as HTML or PDF. The current limitation of doing any of this is also on the availability of getting the full XML file for an article. Free to read is not the same as CC-BY, hence why some of the articles coming from PMC are limited to only the abstract. 

Not sure what you mean by cloning the full elifesciences.org structure. Please use https://groups.google.com/forum/?hl=en#!forum/elife-lens for these types of broader requests and questions.

**Comment by carvaper** [comment]
Dear Ivan,
Thanks for letting me know about the group.
I´m really interested in using Lens and I´m just looking for the best way
to do it.
We also cooperate with a medical library, Medbrary.com  Publications are
showed using HTML5. Do you think Lens could be used there? it would be
great!


On 1 April 2015 at 19:04, Ivan Grubisic <notifications@github.com> wrote:

> Google Scholar only provides links to other resources where the article
> can be found as HTML or PDF. The current limitation of doing any of this is
> also on the availability of getting the full XML file for an article. Free
> to read is not the same as CC-BY, hence why some of the articles coming
> from PMC are limited to only the abstract.
>
> Not sure what you mean by cloning the full elifesciences.org structure.
> Please use https://groups.google.com/forum/?hl=en#!forum/elife-lens for
> these types of broader requests and questions.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elifesciences/lens/issues/107#issuecomment-88550077>.
>



-- 

*Carlos Vázquez*
CEO iMedPub
iMed.pub

**Comment by carvaper** [comment]
Dear Michael and Ivan,
Do you think Lens could be used in Medbrary.com?
Publications are uploaded as .pdf and displayed as HTML5. Would it be
possible to create a new page for visualizing the publications at Lens
using Lens?
Thanks!

On 1 April 2015 at 09:45, Michael Aufreiter <notifications@github.com>
wrote:

> You can find contact information here: http://substance.io/about
>
> We've usually run through several stages when we deployed Lens for a new
> journal.
>
> 1) A demo with a limited set of test articles (3-4 weeks dev)
> 2) A pilot that can be launched (1-3 months dev)
> 3) Polish iterations (based on feature requests)
> 4) Official launch as soon as display quality meets the requirements
>
> We charge on an hourly basis, and can provide estimates for individual
> work packages. How much budget is needed depends on how good the quality of
> the source XML files is and how many customisations are requested.
>
> -- Michael
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elifesciences/lens/issues/107#issuecomment-88382641>.
>



-- 

*Carlos Vázquez*
CEO iMedPub
iMed.pub
