### ISSUE TITLE
Table display issues in Lens

### ISSUE THREAD

**Issue by JGilbert-eLife** [elifesciences/lens#111]
There seem to a couple of issues with table display in Lens, which I believe are widespread:

First, the multi-part table 2 in 04251 (http://elifesciences.org/content/4/e04251/T2) is only showing up as the first part in Lens (http://lens.elifesciences.org/04251/index.html?_ga=1.175887338.931356723.1338218134#figures/all/table_2/fullscreen). I have yet to find another example of a table like this but I believe we have published others.

Secondly, footnotes in tables not showing up in Lens at all. See http://elifesciences.org/content/4/e04251/T1 as compared to http://lens.elifesciences.org/04251/index.html?_ga=1.175887338.931356723.1338218134#figures/all/table_1/fullscreen; http://elifesciences.org/content/4/e04986/T1 as compared to http://lens.elifesciences.org/04986/index.html?_ga=1.181245551.931356723.1338218134#figures/all/table_1/fullscreen etc

**Comment by JGilbert-eLife** [comment]
Have just found a second example of the first issue, in 03568:

http://elifesciences.org/content/3/e03568/T1

http://lens.elifesciences.org/03568/index.html?_ga=1.84072401.931356723.1338218134#figures/all/table_1/fullscreen

**Comment by gnott** [comment]
Table footnotes was not fixed yet, but will be worked on soon from a JIRA ticket.
