### ISSUE TITLE
Mathjax extension from their CDN not found

### ISSUE THREAD

**Issue by gnott** [elifesciences/lens#112]
Running Lens 2.0.0 Beta 1, locally, inspector reports

```
GET http://cdn.mathjax.org/mathjax/latest/extensions/CHTML-preview.js?rev=2.4-beta-2 
404 Not Found
```

I'm not sure if this is required but it doesn't break the Lens.

**Comment by michael** [comment]
Where does this get loaded? I don't see it.

What should be included is the official MathJax distribution:

```html
<script type="text/javascript" src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>
```

**Comment by michael** [comment]
Sorry now I see. This was related to an extension that only existed for MathJax beta. Will fix and rebundle.

**Comment by gnott** [comment]
Works in Beta 2 thanks
