### ISSUE TITLE
Font awesome CSS classes for icons

### ISSUE THREAD

**Issue by gnott** [elifesciences/lens#113]
Running Lens 2.0.0 Beta 1, the figure headers are missing the expand and view icons.

Example fixes,

```
<i class="icon-resize-full"></i>

Change to

<i class="fa fa-expand"></i>
```

```
<i class="icon-eye-open"></i>

Change to

<i class="fa fa-eye"></i>
```

There could be some others for the close icons, etc.

**Comment by michael** [comment]
Oh indeed it seems like I missed updating some. Let me double check. You have loaded font-awesome 4.2.0?

**Comment by gnott** [comment]
Font-awesome was loading ok. Your changes in beta2 fixed the eye and expander icon.
