### ISSUE TITLE
eye icon in resource pane has overloaded functionality

### ISSUE THREAD

**Issue by IanMulvany** [elifesciences/lens#127]
when I click the eye icon from within a resource pane that I have selected, then it highlights and unhighlits the selected resource. 

when I unclick the eye icon on a resource, where I have come in from another pane, it clears that pane and sends me back to the previous pane that I was viewing. 

We have an open question on whether this inconsistency is a good user experience or not.

**Comment by michael** [comment]
I also had a problem with that, as you would not expect the change of a panel when you simply untoggle an item. This behavior has already been fixed in the `ui-iteration` branch, as soon as we have fixed the remaining glitches this would go back into master, if I have your go for it?

**Comment by michael** [comment]
Btw: do you like the improved UI?

- cards don't use so much space anymore
- context toggles sit above the resources panel again

![image](https://cloud.githubusercontent.com/assets/2931/8057604/17b21988-0eb3-11e5-9cc3-26a5fc64a97b.png)

**Comment by IanMulvany** [comment]
This is much better UI. Do you have an ETA for this being release ready?

**Comment by michael** [comment]
It's essentially ready. I will merge with master soon (next 2-3 weeks) after we polished everything a bit.
I think what it needs is a bit of testing with the eLife corpus before we put it live. Maybe we should prepare a test deploy to `lens-dev.elifesciences.org`.
