### ISSUE TITLE
Supplementary material download link to blank URL

### ISSUE THREAD

**Issue by gnott** [elifesciences/lens#132]
E.g. http://lens.elifesciences.org/09343/#figures/supplement_1

This supplementary-material tag has an ``<ext-link>`` (which is linked correctly). There is no ``<media>`` tag specifying a file to be downloaded, but the Download link still appears.

This behaviour is also the same on the current Release Candidate version.

**Comment by CAYdenberg** [comment]
Is this still an issue @gnott ?

**Comment by gnott** [comment]
I think it's no longer an issue by way of the "Additional files" are not shown. I'll close this issue - thanks.
