### ISSUE TITLE
Animated gifs are not supported

### ISSUE THREAD

**Issue by nlisgo** [elifesciences/lens#137]
The following eLife article has some figures which are animated gifs: http://elifesciences.org/content/3/e03318

Here is a relevant figure landing page: http://elifesciences.org/content/3/e03318/F5

Here is the figure output in lens: http://lens.elifesciences.org/03318/#figures/figure_5

**Comment by gnott** [comment]
We may want to ensure ".gif" file extension is added to the fig tag to indicate these, whereas normal JPG fig tags have no file extension specified (which are typically supplied as TIF and later converted to JPG).

**Comment by CAYdenberg** [comment]
Here is the NLM XML for that figure:

```xml
<fig id="fig5" position="float">
  <object-id pub-id-type="doi">10.7554/eLife.03318.007</object-id>
  <label>Animation 1.</label>
  <caption>
    <title>
      3D reconstruction of the bacterial meta3C contact matrix.
    </title>
    <p>
      <bold>DOI:</bold>
      <ext-link ext-link-type="doi" xlink:href="10.7554/eLife.03318.007">http://dx.doi.org/10.7554/eLife.03318.007</ext-link>
    </p>
  </caption>
  <graphic xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="elife03318f005"/>
</fig>
```

So it doesn't seem there's any way for Lens to tell that this should be a gif and not a jpg.

**Comment by gnott** [comment]
This is a sample of the animated gif JATS XML. The plan is to change the eLife assets configuration to recognise the ".gif" files, other figure graphics will have ".tif" extensions.

```
<fig id="fig5" position="float">
<object-id pub-id-type="doi">10.7554/eLife.03318.007</object-id>
<label>Animation 1.</label>
<caption>
<title>
3D reconstruction of the bacterial meta3C contact matrix.
</title>
<p>
<bold>DOI:</bold>
<ext-link ext-link-type="doi" xlink:href="10.7554/eLife.03318.007">http://dx.doi.org/10.7554/eLife.03318.007</ext-link>
</p>
</caption>
<graphic xlink:href="elife-03318-fig2-v1.gif"/>
</fig>
```

**Comment by gnott** [comment]
Animated gifs are supported now with https://github.com/elifesciences/lens/pull/147  in combination with eLife updated gif file formating as in the example above.
