### ISSUE TITLE
Appendices do not appear

### ISSUE THREAD

**Issue by Melissa37** [elifesciences/lens#141]
Example: http://lens.elifesciences.org/05808/index.html

**Comment by withanage** [comment]
@Melissa37  ist it the #133 same like  this one, do you only have  it in IE?

**Comment by Melissa37** [comment]
Hi there

It is not the same issue. I use Chrome and Firefox

Melissa

**Comment by CAYdenberg** [comment]
Looks like it simply isn't supported right now. I think the appropriate place to do it would be under ElifeConverter.enhanceArticle, along with the article commentary and author responses.

However, I know there were plans to support Supplementary Material at some point and maybe it makes more sense to do it alongside that.

**Comment by michael** [comment]
Hi @CAYdenberg. There will be some efforts in April to bring the Lens model closer to JATS. Essentially we want to supports JATS in for editing in Lens Writer and JATS out with preserving markup that's not owned by the editor (e.g. the specific-use attribute). I hope we can also address some of the general converter issues in that iteration.

**Comment by withanage** [comment]
JATS  for editing in Lens Writer is a good aspect, where we are also interested.

**Comment by CAYdenberg** [comment]
Makes sense. Let me know if you need alpha testers etc..

**Comment by pkra** [comment]
Note https://github.com/elifesciences/lens/commit/a3c0bc545482ff1af8c31cb4ed0a9daf9f7eb40b

**Comment by gnott** [comment]
Fixed in https://github.com/elifesciences/lens/pull/204, for eLife at least.
