### ISSUE TITLE
Links to sections do not work

### ISSUE THREAD

**Issue by pkra** [elifesciences/lens#159]
(Moving this from https://github.com/AmerMathSoc/AMS-Lens/issues/46).

Links pointing to sections do not do (much -- they open the TOC panel but nothing more it seems).

XML looks like

``` xml
In Section <xref rid="ltxid49" ref-type="sec">6</xref> we
[...]
<sec id="ltxid49" disp-level="section">  ... </sec>
```

which seems fine.

I thought the expected behavior would be to open the TOC and highlight the relevant entry. Alternatively, the links would scroll to the heading of the referenced section. 

Is this a regression?

**Comment by gnott** [comment]
Was this fixed @pkra? It seems so based on the related issue.

**Comment by pkra** [comment]
> Was this fixed @pkra?

I don't recall but the OP has it marked as `done` so I would assume. 

FYI AMS Lens development stopped a year ago (and never entered production).

**Comment by gnott** [comment]
Thanks Peter. I might be closing some more issues if I think they're resolved in order to clean up the issue list here.
