### ISSUE TITLE
kwd handling does not support complex markup

### ISSUE THREAD

**Issue by pkra** [elifesciences/lens#161]
(Moving this from https://github.com/AmerMathSoc/AMS-Lens/issues/56)

Keywords in JATS can contain complex markup (in particular `inline-formula`) but existing converters only grab textContent from them, e.g., https://github.com/elifesciences/lens/blob/b95caa7f31aba72ce8e39177a87cad892b1764cc/extensions/math/math_converter.js#L599 / https://github.com/elifesciences/lens/blob/2574f0036c548fd7f71e436b6a74f8be9c4e4c33/converter/elife_converter.js#L264.

**Comment by obuchtala** [comment]
Fixed via https://github.com/elifesciences/lens/pull/175
