### ISSUE TITLE
Where did the gulpfile go?

### ISSUE THREAD

**Issue by blahah** [elifesciences/lens#162]
Building with `gulp` requires `gulpfile.js`, which is missing from the repo. I see the AMS fork has one - where the one for this repo go?

**Comment by michael** [comment]
The lens repo is considered library code, so you would have a gulpfile in your integration project. E.g. see: https://github.com/elifesciences/lens-starter or https://github.com/elifesciences/lens-elife

**Comment by blahah** [comment]
gotcha - thanks.  By the time I'd got to the gulp part of the README I didn't realise I was still in the section that talked about `lens-starter`
