### ISSUE TITLE
Bold in Tables doesn't display

### ISSUE THREAD

**Issue by sianroderick** [elifesciences/lens#169]
The bold highlights in the tables in Lens aren't displaying.  Compare Table 1 http://lens.elifesciences.org/05005/index.html?_ga=1.252850569.1075872571.1424876576#figures/html_table_1/fullscreen with https://elifesciences.org/content/4/e05005/table1

**Comment by gnott** [comment]
It looks like the `<table>` content is taken from the XML verbatim and put into a Lens "html_table" node.

Since the table contains `<bold>` JATS tags, then in the HTML browser they are not interpreted as `<b>` tags.

**Comment by gnott** [comment]
Fixed for eLife in ``elife_converter.js``using HTML tag rewrites using the ``enhanceTable()`` hook. In PR https://github.com/elifesciences/lens/pull/205.
