### ISSUE TITLE
Supplemental files missing

### ISSUE THREAD

**Issue by sianroderick** [elifesciences/lens#171]
Links to "Supplemental files" don't lead anywhere, and the files and captions don't appear to be available, e.g. http://lens.elifesciences.org/06763/index.html#content/figure_reference_181

Is this a known issue?

**Comment by gnott** [comment]
Could be working now @sianroderick ?  I'm not sure the "#content/figure_reference_181" anchor still exists, but I see some "Supplementary file" panels.

**Comment by sianroderick** [comment]
Thanks, @gnott .  It all looks good to me!
