### ISSUE TITLE
Institution missing in one affiliation in 14874

### ISSUE THREAD

**Issue by JGilbert-eLife** [elifesciences/lens#172]
On the info tab in 14874, the affiliation for Cha San Koh and Andrei A Korostelev is missing it's institution. It should be:

RNA Therapeutics Institute, Department of Biochemistry and Molecular Pharmacology, University of Massachusetts Medical School, Worcester, United States

and is showing instead as:

RNA Therapeutics Institute, Department of Biochemistry and Molecular Pharmacology, Worcester, United States

![screen shot 2016-06-09 at 10 18 57](https://cloud.githubusercontent.com/assets/1785305/15925344/a9095176-2e2e-11e6-90dd-cd4ae6755be8.png)

This is only affecting this affiliation, the other one appears fine. At a glance, I can't see any problems with the tagging and it is all showing fine on the eLife site/in the PDF.

**Comment by JGilbert-eLife** [comment]
Follow on this, Sian has pointed out this might be an issue there being two sets of `<institution>` tags in the affiliation - one for the institution itself and the other preceeding it with an attribute content-type="dept". Could this issue be being caused by Lens only picking up the first institution tags, even though this is actually the department? 

`<aff id="aff2"><label>2</label><institution content-type="dept">RNA Therapeutics
                        Institute, Department of Biochemistry and Molecular
                        Pharmacology</institution>, <institution>University of Massachusetts Medical
                        School</institution>, <addr-line><named-content content-type="city"
                            >Worcester</named-content></addr-line>, <country>United
                    States</country></aff>`

**Comment by gnott** [comment]
Should be fixed now https://lens.elifesciences.org/14874/#info/contributor_2  Yes @JGilbert-eLife ?
