### ISSUE TITLE
Nested Lists with JATS/NLM tags (list and list-item) repeat data in Lens

### ISSUE THREAD

**Issue by juanCure** [elifesciences/lens#196]
Hi @michael I have a sample of xml jats where there is a nested list and when it is converted through Lens the data of the sublist appear in the its corresponding level but after it is repeated in the upper level too. This is the sample:

```
<list id="mylist" list-type="bullet">
        <list-item><p>A</p></list-item>
        <list-item><p>B</p></list-item>
        <list-item><p>C</p></list-item>
        <list-item>
          <p>D
            <list id="mysublist" list-type="ordered">
                <list-item><p>E</p></list-item>
           </list>
          </p>
        </list-item>
 </list>
```

This sample produces the following result:

<ul>
  <li>A</li>
  <li>B</li>
  <li>C</li>
  <li>D</li>
    <ol>
    <li>E</li>
    </ol>
  </li>
   <li>E</li>
</ul>

I would like to know if someone has the same trouble with the nested lists?, greetings.

**Comment by gnott** [comment]
I can repeat this, and looks like a bug to me. Thanks for the report @juanCure.

**Comment by gnott** [comment]
One example for eLife is https://lens.elifesciences.org/12470/. Previewing this article on the develop branch now has removed the duplicate list items (which should be deployed soon for eLife).
