### ISSUE TITLE
export modified JSON as XML

### ISSUE THREAD

**Issue by nathandunn** [elifesciences/lens#201]
Is there a way to export the modified JSON as a genetics XML using this library?

**Comment by gnott** [comment]
Are there more details you could provide? I have a feeling Lens does not do this already.

**Comment by nathandunn** [comment]
I agree that I don't think it does either. 

The goal would be to have it take the imported JSON / Article object, make modifications to it (e.g,. insert link data) and then re-export the XML into the original format with those modifications. 

I think we can hack around that, but was unsure if there was a better approach.

**Comment by gnott** [comment]
Exporting the JSON to XML was a feature that did not get implemented I believe, although the possibility to do it was raised before. It might be something in line with the Texture project https://github.com/substance/texture where you might want to ask there too.

**Comment by nathandunn** [comment]
Thanks.  That looks great as well.   Was not aware of it.  Will definitely have a look.

Nathan

**Comment by nathandunn** [comment]
That looks like it will work.  Thanks.

**Comment by nathandunn** [comment]
https://github.com/substance/texture#usage
