### ISSUE TITLE
Incorporating Lens

### ISSUE THREAD

**Issue by willgdjones** [elifesciences/lens#208]
Hi all - just wanted to say that I think Lens is an awesome project which makes viewing scientific much more enjoyable!

We are incorporating Lens into in a feature where we are generating personalised content based on a users' genetic data. I have been trying to do two things without success as of yet, and it would be great if someone could point me in the right direction.

- We really like the full page split-screen functionality, but would like to incorporate it as an inline element within a web page so that it doesn't take up the entire screen. Is there are way to do this?

- As I understand, the XML that defines the content of the article is loaded in via a script when the page loads:

e.g. 
```
var documentURL = "/path/to/xml";
	  $(function() {
		// Create a new Lens app instance
		// --------
		//
		// Injects itself into body
		var app = new window.Lens({
		  document_url: qs.url ? decodeURIComponent(qs.url) : documentURL
		});
		app.start();
		window.app = app;
	  });
```

Is there a way for Lens to use XML data that is already inside the HTML instead of a file that is loaded externally?

Thanks in advance for you help!

**Comment by gnott** [comment]
Hey William!  Were you able to get any further in your attempts?

On https://elifesciences.org, the Lens pages are available from article pages when you click the "Side by side" link from the left side navigation links. It loads the Lens page in an ``<iframe>``. It is inline, in a way.

I think you could probably attach the Lens view to an element on the page, as well to load new data on-the-fly. For example, in eLife Lens you can drag-and-drop a new article XML file from your computer and it will render the file. If you have some more specifics about what you want to do, those details might suggest the best next step to try.

**Comment by willgdjones** [comment]
Hi @gnott - yes that looks like it could very well work. Thanks for the suggestion!
