### ISSUE TITLE
eLife videos not loading

### ISSUE THREAD

**Issue by gnott** [elifesciences/lens#94]
The configuration for eLife media / videos assumes the URL for each video is predictable and does not change, re: https://github.com/elifesciences/lens-converter/blob/master/src/configurations/elife.js

The third party video provider confirms the URL for each video file (mp4, webm, etc.) is not predictable. The URL to the video files may also change over time.

The video provider does have an API to query these values.

Some options to choose from:

1. Use the API at the time the time of article conversion to look up the video file URL
1. Use the API at the time the video is played in lens. The video thumbnails can be loaded from the eLife CDN (they already exist)
1. Create an eLife service / proxy / web direct that can provide a predictable and unchanging URL for the video file. It must use the video API to either lookup the URL in real-time, or keep a cache of values from the API.

Or other options?

**Comment by michael** [comment]
Integrated and tested our new video url resolving API. Works now.
